Repository Devocean-TechWave/OLOL-backend, pull requests merged in 2024-08, with the labels that each got.

#10 [Feature] Add join, default image #6
  build.gradle
  images/profile/default_profile.PNG
  src/main/java/com/techwave/olol/OlolApplication.java
  src/main/java/com/techwave/olol/common/BaseEntity.java
  src/main/java/com/techwave/olol/global/exception/ApiException.java
  src/main/java/com/techwave/olol/global/exception/ApiExceptionHandler.java
  src/main/java/com/techwave/olol/global/exception/Error.java
  src/main/java/com/techwave/olol/login/auth/JwtAuthenticationFilter.java
  src/main/java/com/techwave/olol/login/auth/JwtProvider.java
  src/main/java/com/techwave/olol/login/auth/JwtUtil.java
  src/main/java/com/techwave/olol/login/auth/RestAuthenticationEntryPoint.java
  src/main/java/com/techwave/olol/login/auth/TokenAccessDeniedHandler.java
  src/main/java/com/techwave/olol/login/auth/UserPrincipal.java
  src/main/java/com/techwave/olol/login/config/JwtProperties.java
  src/main/java/com/techwave/olol/login/config/KakaoProperties.java
  src/main/java/com/techwave/olol/login/config/SecurityConfig.java
  src/main/java/com/techwave/olol/login/constant/AuthType.java
  src/main/java/com/techwave/olol/login/constant/GrantType.java
  src/main/java/com/techwave/olol/login/controller/TestController.java
  src/main/java/com/techwave/olol/login/dto/AuthTokenDto.java
  src/main/java/com/techwave/olol/login/dto/TokenDto.java
  src/main/java/com/techwave/olol/login/dto/reponse/ApiErrorResponse.java
  src/main/java/com/techwave/olol/login/dto/reponse/KakaoAuthResponse.java
  src/main/java/com/techwave/olol/login/dto/reponse/KakaoUserInfoResponse.java
  src/main/java/com/techwave/olol/login/model/RefreshToken.java
  src/main/java/com/techwave/olol/login/repository/RefreshTokenRepository.java
  src/main/java/com/techwave/olol/login/service/LoginService.java
  src/main/java/com/techwave/olol/login/util/RequestUtil.java
  src/main/java/com/techwave/olol/user/constant/GenderType.java
  src/main/java/com/techwave/olol/user/controller/MyPageController.java
  src/main/java/com/techwave/olol/user/controller/UserController.java
  src/main/java/com/techwave/olol/user/dto/UserDto.java
  src/main/java/com/techwave/olol/user/dto/request/EditUserRequest.java
  src/main/java/com/techwave/olol/user/dto/request/KakaoJoinRequest.java
  src/main/java/com/techwave/olol/user/model/User.java
  src/main/java/com/techwave/olol/user/repository/UserRepository.java
  src/main/java/com/techwave/olol/user/service/ImagesService.java
  src/main/java/com/techwave/olol/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
Labels: enhancement

#14 스웨거 및 스프링 시큐리티 설정
  src/main/java/com/techwave/olol/OlolApplication.java
  src/main/java/com/techwave/olol/global/config/SwaggerConfig.java
  src/main/java/com/techwave/olol/login/auth/JwtAuthenticationFilter.java
  src/main/java/com/techwave/olol/login/config/SecurityConfig.java
  src/main/java/com/techwave/olol/login/config/SecurityProperties.java
  src/main/java/com/techwave/olol/user/controller/MyPageController.java
  src/main/java/com/techwave/olol/user/controller/UserController.java
  src/main/resources/application.yml
Labels: documentation, enhancement

#16 미션 생성, 조회, 인증
  build.gradle
  src/main/java/com/techwave/olol/global/config/S3Config.java
  src/main/java/com/techwave/olol/mission/controller/MissionController.java
  src/main/java/com/techwave/olol/mission/domain/Mission.java
  src/main/java/com/techwave/olol/mission/dto/request/ReqMissionDto.java
  src/main/java/com/techwave/olol/mission/repository/MissionRepository.java
  src/main/java/com/techwave/olol/mission/service/MissionService.java
  src/main/java/com/techwave/olol/user/domain/User.java
  src/test/java/com/techwave/olol/mission/service/MissionServiceTest.java
Labels: enhancement

#18 [Fix] login, user 수정
  src/main/java/com/techwave/olol/login/auth/JwtProvider.java
  src/main/java/com/techwave/olol/user/dto/SecurityUser.java
  src/main/java/com/techwave/olol/user/service/UserService.java
Labels: bug

#20 미션 삭제
  src/main/java/com/techwave/olol/mission/controller/MissionController.java
  src/main/java/com/techwave/olol/mission/domain/Mission.java
  src/main/java/com/techwave/olol/mission/service/MissionService.java
  src/main/java/com/techwave/olol/user/repository/UserRepository.java
  src/test/java/com/techwave/olol/mission/service/MissionServiceTest.java
Labels: enhancement

#22 메인 화면 미션 조회
  src/main/java/com/techwave/olol/mission/controller/MissionController.java
  src/main/java/com/techwave/olol/mission/dto/GivenMissionDto.java
  src/main/java/com/techwave/olol/mission/dto/ReceivedMissionDto.java
  src/main/java/com/techwave/olol/mission/dto/response/RespMissionDto.java
  src/main/java/com/techwave/olol/mission/service/MissionService.java
  src/test/java/com/techwave/olol/mission/service/MissionServiceTest.java
Labels: enhancement
